#!/usr/bin/ruby
require 'json'
require 'time'
require 'yaml'
require 'i2c'
require 'gpio'
require 'couchrest'
require 'simple-graphite'
require 'socket'
require 'open-uri'
require 'httparty'
require 'nokogiri'


require File.dirname(__FILE__)+'/lib/boattr/sensors/sensors.rb'
require File.dirname(__FILE__)+'/lib/boattr/data/data.rb'
require File.dirname(__FILE__)+'/lib/boattr/dashing/dashing.rb'
require File.dirname(__FILE__)+'/lib/boattr/config/config.rb'
require File.dirname(__FILE__)+'/lib/boattr/control/control.rb'
require File.dirname(__FILE__)+'/lib/boattr/control/pump/pump.rb'
