boattr:
   basename: boat
   description: "boattr dev box"
i2c:
   i2cAdc:
     adc1:
       address: 0x28
       dev:  "I2C2"
     adc2:
       address: 0x20
       dev: "I2C2"
       type: "arduino"
       description: "arduino uno analog ports via i2c"
couchdb:
   host: localhost
dashing:
   host: localhost
   auth: YOUR_AUTH_TOKEN
graphite:
   host: 10.70.60.1
sensors:
   temp:
     in:
       address: 10-0008029674ee
       description: "inside temperature"
     out:
       address: 10-000802964c0d
     cylinder:
       address: 10-000802961f0d
     stove:
       address: 10-00080296978d
     bed:
       address: 28-00000566f3b8
   current:
     solar:
       address:
         adc: adc0
         pin: 2
       model:  acs712-20
       mode:  src
     genny:
       address:
         adc: adc0
         pin: 1
       model:  acs714
       mode:  src
     lights:
       address:
         adc: adc0
         pin: 2
       model:  acs712-20
       mode:  load
     pumps:
       address:
         adc: adc0
         pin: 3
       model:  acs714
       mode:  load
       disabled: true
     ring:
       address:
         adc: adc0
         pin: 4
       model:  acs714
       mode:  load
     fridge:
       address:
         adc: adc0
         pin: 5
       model:  acs714
       mode:  load
   voltage:
     batteries:
       address:
         adc: adc1
         pin: 6
   depth:
     watertank:
       address:
         adc: adc0
         pin: 7
