boattr:
   basename: <%= @basename %>
   description: <%= @description %>
   i2cBus: "<%= @i2cBus %>"
   i2cAdcAddress: "<%= @i2cAdcAddress %>"
database:
   host: "<%= @db_host %>"
   dir:  "<%= @db_dir %>"
dashboard:
   host: "<%= @dash_host %>"
   dir:  "<%= @dash_dir %>"   
   auth: "<%= @dash_auth %>"   
graphite:
   host: "<%= @graph_host %>"   
sensors:
   temp:
      bed: 28-12345677
      out: 10-23213212
   current:
      solar:
        name: solar
        pin:  2
        type:  acs712
        mode:  src
      genny:
        name: genny
        pin:  2
        type:  acs709
        mode:  src
      ring:
        name: ring
        pin:  2
        type:  acs712
        mode:  load
   voltage:
      batteries:
        name: batteries
        pin: 3
